services:
  - type: web
    name: expense-tracker
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn expense_tracker.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: expense_tracker.settings
      - key: PYTHON_VERSION
        value: 3.11
